name: Build Typst document
on: 
  push:
    paths-ignore:
      - 'main.pdf'

permissions:
  contents: write
  
jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: main.typ
      - name: List files
        run: ls -R
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: typst-output
          path: main.pdf
      - name: Test auth
        run: git ls-remote https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      - name: Commit PDF to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add main.pdf
          git commit -m "Add generated PDF" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
